apiVersion: v1
kind: ReplicationController
metadata:
  name: myjavaapp-rc
spec:
  replicas: 5
  selector: 
    app: myjavaapp
  template:
    metadata:
      name: myjavaapp
      labels:
        app: myjavaapp
    spec:
      containers:
        - name: first-container
          image: rohitsharma93/myjavaimagemay0922
          ports:
            - containerPort: 8080
