apiVersion: v1
kind: ReplicationController
metadata:
  name: mynginx-rc
spec:
  replicas: 5
  selector: 
    app: mynginx
  template:
    metadata:
      name: myapp
      labels:
        app: mynginx
    spec:
      containers:
        - name: first-container
          image: nginx
          ports:
            - containerPort: 80
